[[protocols]]
name = "OVT HD"
protocol = "nec"
variant = "nec32"

[protocols.scancodes]

0xf1 = "KEY_POWER"
0x1fd80 = "KEY_VOLUMEUP"
0x1fdd6 = "KEY_BACK"
0x1fd91 = "KEY_PLAYPAUSE"
0x1fdd0 = "KEY_FORWARD"
0x1fdd2 = "KEY_DOWN"
0x1fd81 = "KEY_VOLUMEDOWN"
0x1fdca = "KEY_UP"
0x1fd87 = "KEY_0"
0x1fd92 = "KEY_1"
0x1fd93 = "KEY_2"
0x1fdcc = "KEY_3"
0x1fd8e = "KEY_4"
0x1fd8f = "KEY_5"
0x1fdc8 = "KEY_6"
0x1fd8a = "KEY_7"
0x1fd8b = "KEY_8"
0x1fdc4 = "KEY_9"
0x1fdc1 = "KEY_RIGHT"
0x1fd99 = "KEY_LEFT"
0x1fd98 = "KEY_MENU"
0x1fd88 = "KEY_LIST"
0x1fdce = "KEY_OK"
0x1fd9c = "KEY_MUTE"
0x1fd82 = "KEY_UNDO"
0x1fdc5 = "KEY_EXIT"
0x1fd85 = "KEY_CHANNELUP"
0x1fd86 = "KEY_CHANNELDOWN"
0x1fd8d = "KEY_STOP"
0x1fd95 = "KEY_LANGUAGE"
0x1fdd1 = "KEY_RECORD"
0x1fdcd = "KEY_REWIND"
0x1fd89 = "KEY_RED"
0x1fd84 = "KEY_GREEN"
0x1fdd9 = "KEY_YELLOW"
0x1fd96 = "KEY_BLUE"
0x1fdcf = "KEY_FAVORITES"
0x1fdc3 = "KEY_AUDIO"
